### PR TITLE
unit struct serialize as 0u8 and deserialize

### PR DESCRIPTION
**Pull request by ailisp**
Was planning to do also unit enum & tag only enum, but this seems more complicated than I thought. So asking for a review first.

### CODE REVIEW

**Comment by fckt** [comment]
Why is it necessary to have a byte-representation of a unit struct? Shouldn't it be ethereal?

**Comment by nearmax** [comment]
In the vulnerability report, they mention two causes:
* We deserialize certain types by first creating an array of zeros and then filling it in with the bytes without measuring exactly how many bytes were filled in;
* We serialize unit types with no bytes. (Btw, unit struct and unit enum are not the only types that have 0-bytes representation, e.g. `()` have zero bytes representation too, but they forgot about it).

The first one is problematic because once we reach the end of the input sequence we are still able to deserialize unlimited number of elements from an empty sequence, making us vulnerable to exhaustion attacks.

They suggest that the second one is problematic because someone can create a serialized sequence that claims to have 2^32 elements of some 0-byte type and then we would have to create a vector with 2^32 elements. Creating a vector of 2^32 elements takes time and memory. Fortunately, `Vec<T>` does not allocate when `size_of::<T>() == 0`, so RAM is not an issue. We can solve the time issue by not performing this loop here if `size_of::<T>() == 0` https://github.com/nearprotocol/borsh/blob/master/borsh-rs/borsh/src/de/mod.rs#L132 Other std collections, like `HashMap`, `HashSet`, `BTreeMap`, `BTreeSet` are not susceptible to exhaustion attacks, because if someone uses `*Set` with 0-byte types then they have to explicitly define hash/comparators on it which would mean they know what they are doing. Similarly, someone would know what they are doing if they use 0-byte key types in `*Map`. 0-byte values in `*Map` are not a problem since keys are not going to be 0-byte types.

**Comment by nearmax** [comment]
> The issue is solvable by just adding an if check before the loop mentioned in the comment.

Correction, we need to not only add an if check but do something like `vec![T::deserialize()?; len]`

**Comment by ailisp** [comment]
will close this and reopen a pr. but seems stuck with rust trait checker:
```rust
        let len = u32::deserialize(reader)?;
        if size_of::<T>() == 0 {
            Ok(vec![T::deserialize(reader)?; len as usize]) // <- here rust insist T needs to have `Clone` trait. is there a way to assert this trait, since it is either unit struct, unit enum or ().
        } else {
```

**Comment by nearmax** [comment]
> will close this and reopen a pr. but seems stuck with rust trait checker:
> 
> ```rust
> if size_of::<T>() == 0 {
>     Ok(vec![T::deserialize(reader)?; len as usize]) // <- here 
> // rust insist T needs to have `Clone` trait.
> // is there a way to assert this trait, since it is
> // either unit struct, unit enum or ().
> } else {
> ```

I consulted Rust channel. It seems like if we do the following:
```
let len = u32::deserialize(input)?;
        let mut result = Vec::with_capacity(hint::cautious::<T>(input.rem_len()? as u32, len));
        if size_of::<T>() == 0 {
        for _ in 0..len {
            result.push(T::deserialize(input).unwrap());
        }
        } else {
        for _ in 0..len {
            result.push(T::deserialize(input)?);
        }
        }
        Ok(result)
```

the compiler should always optimize it out if we use `-C opt-level=3`, see: https://godbolt.org/z/hvzYZ5
We can unwrap because deserializing unit struct cannot ever fail.

We should, however, have a unit test that checks that this is the case (would have to run this test separately with --release flag) by deserializing a vector of 2^30 unit struct elements. And we should comment it and add it to the readme file, that this guarantee only works with compiler optimization turned on.

**Comment by nearmax** [comment]
Actually, we might not need to do anything, besides adding the comment, updating the documentation, and adding a special test. The following code seems to not have a loop: https://godbolt.org/z/iMoBm4

**Comment by ailisp** [comment]
Will add comment/test/doc tomorrow

**Pull request closed without merging**
